### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by StanleyMasinde**
I have added the contributing guidelines

### CODE REVIEW

**Review by joelkanyi — APPROVED** [review]

**Comment by StanleyMasinde** [comment]
Hehe @JoelKanyi Umesoma kweli

**Comment by cyrus43** [comment]
Awesome

**Review by joelkanyi — COMMENTED** [review]
@stannlee i have read it

**Comment by w1lc0x** [comment]
Good hob Stan although nashuku hio English sio yako. It's well composed

**Comment by StanleyMasinde** [comment]
> Good hob Stan although nashuku hio English sio yako. It's well composed

😂😂😂 Hater

**Pull request merged**
